### PR TITLE
Added static filter under result widget

### PR DESCRIPTION
**Pull request by mmoreram**
* By adding the filter configruation option, as an anonymous function with
  a Query parameter, you can add some permanent filters (like Universal filters)
  to reduce the scope of the domain

### CODE REVIEW

**Comment by mmoreram** [comment]
@cv65kr can you review before merging, please?
You can take a look at `simple-search.html` example

**Comment by cv65kr** [comment]
@mmoreram Everything is fine, please add charset tag in head section `<meta charset="UTF-8">` to demo, query is malformed for some chars.

**Comment by mmoreram** [comment]
Oh yes. A sec.

**Comment by mmoreram** [comment]
@cv65kr Pushed meta tags

**Pull request merged**
